### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by Atemu** [seiya-dev/funimation-downloader-nx#1]
Why are all the anime site download tool repos empty now?

**Comment by storm134** [comment]
I was wondering what happend to.

**Comment by Tridagger** [comment]
I was wondering what happend to.

**Comment by UiharuKazari2008** [comment]
Out of date but a copy https://code.acr.moe/kazari/funimation-downloader

**Comment by Tridagger** [comment]
> Out of date but a copy https://code.acr.moe/kazari/funimation-downloader


the latest version 
https://github.com/Tridagger/funi-dl

**Comment by UiharuKazari2008** [comment]
Thanks, the hls download function is broken but using youtube-dl like so you can still get the job accomplished and just use funi-dl to get the stream
`youtube-dl --hls-prefer-ffmpeg $(node ./funi.js -s 37172 -e 0002 -q 0 --novids --nosubs | grep "Stream URL:" | cut -f 2,3 -d ':')`

**Comment by darkhelmet2016** [comment]
You really don't need to do all that just have it direct it to where your cookie file is and use the url from the site. You can instruct youtube dl what settings you want in the config file.

**Comment by storm134** [comment]
anyone know what happened, i know seiya-dev pages where gone for a while,then when they came back they were all empty.Did git-hub spend the account and make the downloader be remove? are they going to be reposted here or some were else? or is seiya-dev done with the downloaders?

**Comment by anidl-git** [comment]
I continuing work of seiya-git, I will post new fixed version of funimation downloader on my page soon

**Comment by Atemu** [comment]
The repos were force-pushed with a nearly empty commit by the owner.

If it was taken down for legal reasons, it'd show a DCMA page explaining the takedown.

>are they going to be reposted here or some were else?

They already were, look a few comments above.

>is seiya-dev done with the downloaders?

This looks like a pretty clear yes to me, I'm just curious why that is.

I don't think we tried pinging them yet. 

@seiya-git care to give us an explanation?  

You're not obligated to by any means but it'd be nice to know.

**Comment by Atemu** [comment]
> I continuing work of seiya-git, I will post new fixed version of funimation downloader on my page soon

Awesome, thank you!

**Comment by storm134** [comment]
that awesome, will you be doing seiya-git crunchyroll and hidive as well?

**Comment by XxUnkn0wnxX** [comment]
it does work but you need to make sure your using hls download 2.2.1 any higher & it breaks. just edit the `package.json` & remove the `^` infront of the value then run npm update & it should grab the older version. or wait till @anidl fixes it...

also @anidl will you be fixing hidive? their API changed again looks like new keys will be needed.

**Comment by anidl-git** [comment]
https://github.com/anidl/funimation-downloader-nx
update version

**Comment by darkhelmet2016** [comment]
@anidl Do you plan on doing the hidive one as well?
