### ISSUE TITLE
What exactly goes in the bin folder?

### ISSUE THREAD

**Issue by stark700** [seiya-dev/funimation-downloader-nx#13]
I dropped the streamlink.exe into

\bin\streamlink\build

but when I try to download an episode, it always runs the executable and tries to install, prompting the usual windows popup when you normally install something

then it did something similar for the TSmuxer

What exactly are you supposed to put in the bin folder?
the EXEs or get the portable zips and throw them into there, renaming as the the paths designation says?

The instructions aren't very clear

**Comment by seiya-git** [comment]
You need portable version or change path to binaries in config.bin.js file.

**Comment by seiya-git** [comment]
For windows use this instead: https://github.com/streamlink/streamlink-portable/releases

**Comment by stark700** [comment]
That part works, but now it looks like I need a portable version of mp4box or something?

The file downloaded, but I got the error I got earlier, except for mp4box.
I got the source code zip for this https://github.com/gpac/gpac/releases/tag/v0.6.0
and renamed the folder to mp4box

**Comment by stark700** [comment]
One additional question, how do you download the other bitrates?

720p sometimes has more than one stream, it says 720p_alt and 720p_alt2 when streamlink starts, but I can't choose them by doing
-q 720p_alt

**Comment by seiya-git** [comment]
> mp4box
Download mp4box binaries from: https://gpac.io/downloads/
> how do you download the other bitrates?
It's almost same quality, and you can add them by yourself to [this string](https://github.com/seiya-dev/funimation-downloader-nx/blob/master/scripts/funidl.js#L61)

**Comment by stark700** [comment]
So I can just use the EXE from this?
https://download.tsi.telecom-paristech.fr/gpac/release/0.7.0/gpac-0.7.0-rev0-gbd5c9af-master-x64.exe

Editing the funi.js didn't allow me to download a different bitrate of the 720p stream. I got the same thing.

tried 720p_alt2, but the normal 720p downloaded.

**Comment by seiya-git** [comment]
No, you need install it first, then move files to bin directory.

Idk, maybe it's just mirrors for better strimming.

**Comment by leptoid** [comment]
Your directory will look like this if you've done it right in windows:
![bin structure](https://user-images.githubusercontent.com/18079714/30134744-c8a6bfa0-931d-11e7-8813-38d1372f07cf.JPG)
and stark - you can use that file, but you have to install it, and move the entire installation into a folder named "mp4box" in the bin folder.  Copying only the exe would leave out all of its dependencies.  Overall, you're on the right track.

**Comment by leptoid** [comment]
I have just updated the script on my PC from scratch.  Everything works as it should but to ensure it all works correctly, you may want to run the following at a command prompt:
`npm -v`
If the version of npm is below 5.4, run the following:
`npm install npm@latest -g`
Test the version again by running the first command.  This got rid of a few strange bugs for me when I was first trying to get the app to function.  I have to use the app because otherwise my videos skip and repeat audio every 10 seconds. :(
