### ISSUE TITLE
Console Characters Cause Files to Fail to Multiplex

### ISSUE THREAD

**Issue by leptoid** [seiya-dev/funimation-downloader-nx#14]
I had this issue before 2.3.3 came out, just with a different character.  In 2.5.0, with the anime "Shimoneta,"  files fail to multiplex.  The files download, they are named the same on the actual filesystem, however, the scripts see the .ts and .meta files differently to the extend that the .ts file's name looks corrupt.

`SHIMONETA_ A Boring World Where the Concept of Dirty Jokes Doesn’t Exist - 02 [720p]`
becomes
`SHIMONETA_ A Boring World Where the Concept of Dirty Jokes Doesn�_Tt Exist - 02 [720p]`

Due to a script seeing these as mismatched file names, the files fail to multiplex.

**Comment by leptoid** [comment]
Changing console font to 'Lucida Console' in conjunction with 'chcp 65001' does not have any effect regarding solving the problem.
`https://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500`

**Comment by leptoid** [comment]
Am I correct in assuming lines 367-372 in funidl.js would need modified to account for this character?
`		// check filename for ts muxer
		fnOutput_bak = fnOutput;
		if(fnOutput_bak.indexOf('.')>-1){
			fnOutput = fnOutput.replace(/\./g,'_');
			fs.renameSync(fnOutput_bak+'.ts', fnOutput+'.ts');
		}`

**Comment by seiya-git** [comment]
Just use custom title for this show:
`-t SHIMONETA`

**Comment by leptoid** [comment]
That works.  I need to make better use of the title flags.  
Thanks!
