### ISSUE TITLE
Error: Livestreamer version

### ISSUE THREAD

**Issue by nolan1989** [seiya-dev/funimation-downloader-nx#15]
I'm receiving an error: Can't import nae: Livestreamer version. Started today, 10/02/2017.

![image](https://user-images.githubusercontent.com/9664889/31103983-bea615dc-a79f-11e7-8cb4-d2d4cca4bf80.png)

**Comment by seiya-git** [comment]
Can you provide me what arguments do you set?

**Comment by nolan1989** [comment]
I use the following in a bat file:

"node" "%~dp0.\scripts\funidl.js" -s 264281 --sel 11 -q 1080p -dub --mkv

in a windows 10 x64 system.

**Comment by seiya-git** [comment]
Something wrong with your streamlink client, try remove spaces from path.

**Comment by nolan1989** [comment]
I also had to update node. Its working now. Thanks for the assist
