### ISSUE TITLE
unable to download since monday

### ISSUE THREAD

**Issue by storm134** [seiya-dev/funimation-downloader-nx#16]
getting this error since monday morning

[INFO] Available audio tracks:
[#53700] Japanese
[#526213] English (selected)
[ERROR] unknown error, body:
 <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=26&xinfo=10-18357853-0%200NNN%20RT%281507692542229%2071%29%20q%280%20-1%20-1%20397%29%20r%283%20-1%29%20B12%284%2c315%2c0%29%20U18&incident_id=163001040042111940-122844306718525066&edet=12&cinfo=04000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 163001040042111940-122844306718525066</iframe></body></html>

Press any key to continue . . .

**Comment by seiya-git** [comment]
@storm134, please, give me title id and episode number.

**Comment by leptoid** [comment]
mine has worked, however, like @seiya-git stated, their servers have been unstable.
