### ISSUE TITLE
VTT Subtitles not working

### ISSUE THREAD

**Issue by Shadowfita** [seiya-dev/funimation-downloader-nx#17]
I've just been testing it out and I can't get VTT subtitles to play when combined with mkvmerge. Using the file itself with VLC runs fine but merged videos don't play nice.

**Comment by Golumpa** [comment]
The new beta uses srt subs. Does this still happen?

**Comment by seiya-git** [comment]
Use latest beta https://github.com/seiya-dev/funimation-downloader-nx/releases
