### ISSUE TITLE
really slow

### ISSUE THREAD

**Issue by storm134** [seiya-dev/funimation-downloader-nx#24]
** Main info: **
not sure if it is and issue but Takes 40 minute to an hour to download one episode. also it some time get stuck on a part and sits there does not time out
Script version: 3.2.6
Show ID:
Episode ID:

** Additional Info: **

**Comment by seiya-git** [comment]
Strange. Do you use proxy?

**Comment by storm134** [comment]
nope, i have a fiber line. what's the normal speed for downloading on the new 3.2.6.
________________________________

**Comment by seiya-git** [comment]
This is strange, because download not was changed. Maybe api gives slow server.

**Comment by storm134** [comment]
it was weird, went back to normal friday. take about 4-5 minutes with version 3.2.6 and 3-4 minutes with version 2.5 must have been an issue on route from my connection. keep up the awesome work. i love this app.
________________________________

**Comment by seiya-git** [comment]
Thanks!
