### ISSUE TITLE
Unable to locate  \scripts\funi.js

### ISSUE THREAD

**Issue by nolan1989** [seiya-dev/funimation-downloader-nx#25]
** Main info: **

So, I haven't downloaded in a while and have to reinstall this. First, it doesn't come with the funi.bat file anymore, so I copied the one I had from an old release(no idea on version)

When I attempt to run it, it throws an error:

module.js:549
    throw err;
    ^

Error: Cannot find module 'E:\funimation-downloader-nx-3.2.6\scripts\funi.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Press any key to continue . . .

I've verified that the bin folder is correct(though it looks like mp4box is now called GPAC on their site) and I've updated everything via NPM. Is there something glaringly obvios that I'm missing? 

If possible, could we get an in-depth install guide for this as well?

Script version: 3.2.6
Show ID: Any
Episode ID: Any

** Additional Info: **

**Comment by seiya-git** [comment]
Path was changed, just edit bat file
