### ISSUE TITLE
Error downloaing subtitles

### ISSUE THREAD

**Issue by storm134** [seiya-dev/funimation-downloader-nx#26]
** Main info: **
Getting UnhandledPromiseRejectionWarning error on subtitles
Script version: 3.2.6
Show ID:551782 (but tried others)
Episode ID: 1

** Additional Info: **
C:\funimation-downloader-nx-3.2.6>node funi.js -s 551782 --dub --sel 1

=== Funimation Downloader NX 3.2.6 ===

[#551782] Re:ZERO -Starting Life in Another World- (2016)
[0001] Re:ZERO -Starting Life in Another World- - #01 The End of the Beginning and the Beginning of the End (49:08) [HD1080, English] (selected)

[INFO] Re:ZERO -Starting Life in Another World- - S1E01 - The End of the Beginning and the Beginning of the End
[INFO] Available audio tracks:
[#562093] English (selected)
[INFO] Selected layer: 7
        Available qualities:
                1: 234p (540KiB/s)
                10: 1080p (9486KiB/s)
                2: 270p (780KiB/s)
                3: 360p (1033KiB/s)
                4: 360p (1765KiB/s)
                5: 540p (2434KiB/s)
                6: 720p (2976KiB/s)
                7: 720p (4270KiB/s)
                8: 810p (6058KiB/s)
                9: 1080p (7844KiB/s)
[INFO] Output filename: [Funimation] Re_ZERO -Starting Life in Another World- - 01 [720p]
[INFO] Starting downloading ts...
File «[Funimation] Re_ZERO -Starting Life in Another World- - 01 [720p].ts» already exists! Rewrite? (y/N): y
[INFO] Deleting «[Funimation] Re_ZERO -Starting Life in Another World- - 01 [720p].ts»...
[INFO] Saving stream to «[Funimation] Re_ZERO -Starting Life in Another World- - 01 [720p].ts»...
[INFO] 5 parts of 370 downloaded [1%] (1m39s)
[INFO] 10 parts of 370 downloaded [3%] (1m34s)
[INFO] 15 parts of 370 downloaded [4%] (1m32s)
[INFO] 20 parts of 370 downloaded [5%] (1m30s)
[INFO] 25 parts of 370 downloaded [7%] (1m37s)
[INFO] 30 parts of 370 downloaded [8%] (1m34s)
[INFO] 35 parts of 370 downloaded [9%] (1m32s)
[INFO] 40 parts of 370 downloaded [11%] (1m30s)
[INFO] 45 parts of 370 downloaded [12%] (1m31s)
[INFO] 50 parts of 370 downloaded [14%] (1m29s)
[INFO] 55 parts of 370 downloaded [15%] (1m27s)
[INFO] 60 parts of 370 downloaded [16%] (1m25s)
[INFO] 65 parts of 370 downloaded [18%] (1m24s)
[INFO] 70 parts of 370 downloaded [19%] (1m22s)
[INFO] 75 parts of 370 downloaded [20%] (1m20s)
[INFO] 80 parts of 370 downloaded [22%] (1m20s)
[INFO] 85 parts of 370 downloaded [23%] (1m19s)
[INFO] 90 parts of 370 downloaded [24%] (1m18s)
[INFO] 95 parts of 370 downloaded [26%] (1m17s)
[INFO] 100 parts of 370 downloaded [27%] (1m15s)
[INFO] 105 parts of 370 downloaded [28%] (1m13s)
[INFO] 110 parts of 370 downloaded [30%] (1m11s)
[INFO] 115 parts of 370 downloaded [31%] (1m10s)
[INFO] 120 parts of 370 downloaded [32%] (1m08s)
[INFO] 125 parts of 370 downloaded [34%] (1m07s)
[INFO] 130 parts of 370 downloaded [35%] (1m05s)
[INFO] 135 parts of 370 downloaded [36%] (1m04s)
[INFO] 140 parts of 370 downloaded [38%] (1m02s)
[INFO] 145 parts of 370 downloaded [39%] (1m01s)
[INFO] 150 parts of 370 downloaded [41%] (59s)
[INFO] 155 parts of 370 downloaded [42%] (58s)
[INFO] 160 parts of 370 downloaded [43%] (57s)
[INFO] 165 parts of 370 downloaded [45%] (56s)
[INFO] 170 parts of 370 downloaded [46%] (55s)
[INFO] 175 parts of 370 downloaded [47%] (53s)
[INFO] 180 parts of 370 downloaded [49%] (52s)
[INFO] 185 parts of 370 downloaded [50%] (50s)
[INFO] 190 parts of 370 downloaded [51%] (49s)
[INFO] 195 parts of 370 downloaded [53%] (48s)
[INFO] 200 parts of 370 downloaded [54%] (46s)
[INFO] 205 parts of 370 downloaded [55%] (45s)
[INFO] 210 parts of 370 downloaded [57%] (43s)
[INFO] 215 parts of 370 downloaded [58%] (42s)
[INFO] 220 parts of 370 downloaded [59%] (41s)
[INFO] 225 parts of 370 downloaded [61%] (39s)
[INFO] 230 parts of 370 downloaded [62%] (38s)
[INFO] 235 parts of 370 downloaded [64%] (36s)
[INFO] 240 parts of 370 downloaded [65%] (35s)
[INFO] 245 parts of 370 downloaded [66%] (34s)
[INFO] 250 parts of 370 downloaded [68%] (32s)
[INFO] 255 parts of 370 downloaded [69%] (31s)
[INFO] 260 parts of 370 downloaded [70%] (30s)
[INFO] 265 parts of 370 downloaded [72%] (29s)
[INFO] 270 parts of 370 downloaded [73%] (27s)
[INFO] 275 parts of 370 downloaded [74%] (26s)
[INFO] 280 parts of 370 downloaded [76%] (24s)
[INFO] 285 parts of 370 downloaded [77%] (23s)
[INFO] 290 parts of 370 downloaded [78%] (22s)
[INFO] 295 parts of 370 downloaded [80%] (20s)
[INFO] 300 parts of 370 downloaded [81%] (19s)
[INFO] 305 parts of 370 downloaded [82%] (17s)
[INFO] 310 parts of 370 downloaded [84%] (16s)
[INFO] 315 parts of 370 downloaded [85%] (15s)
[INFO] 320 parts of 370 downloaded [86%] (13s)
[INFO] 325 parts of 370 downloaded [88%] (12s)
[INFO] 330 parts of 370 downloaded [89%] (11s)
[INFO] 335 parts of 370 downloaded [91%] (9s)
[INFO] 340 parts of 370 downloaded [92%] (8s)
[INFO] 345 parts of 370 downloaded [93%] (7s)
[INFO] 350 parts of 370 downloaded [95%] (5s)
[INFO] 355 parts of 370 downloaded [96%] (4s)
[INFO] 360 parts of 370 downloaded [97%] (3s)
[INFO] 365 parts of 370 downloaded [99%] (1s)
[INFO] 370 parts of 370 downloaded [100%] (0s)
[INFO] Video downloaded!

[INFO] Downloading subtitles...
(node:1208) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: ms.padStart is not a function
(node:1208) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by storm134** [comment]
Just wanted to add this error just started since i upgrade to windows 10 spring (version 1803)

**Comment by seiya-git** [comment]
Thanks for reporting!

**Comment by seiya-git** [comment]
Strange, witch version of Node do you use?

**Comment by storm134** [comment]
Hey sorry for taking so long i am using node version 7.9.0 for windows. i have windows 10 version 1803. as i said was working before i did the update which would have been windows version 1709.
________________________________

**Comment by storm134** [comment]
after sending the first email . I checked and see that a new version was available so I update to version 8.11.2and that seems to have fixed the issue. you can close the bug. the awesome app is alive again! thanks for the help
________________________________
