### ISSUE TITLE
Funimation Search error undefined body

### ISSUE THREAD

**Issue by danielkp1234** [seiya-dev/funimation-downloader-nx#29]
** Main info: **
So i get this error trying to search for show with node funi.js --search My Hero Academia
=== Funimation Downloader NX 3.2.8 ===

[ERROR] Error: undefined, body:
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=20&xinfo=6-13748416-0%200NNN%20RT%281540928223821%2060%29%20q%280%20-1%20-1%200%29%20r%280%20-1%29%20B16%20U18&incident_id=723000690116569855-58467067725284438&edet=16&cinfo=ffffffff" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 723000690116569855-58467067725284438</iframe></body></html>
Script version: 3.2.8
Show ID:
Episode ID:

** Additional Info: **

**Comment by seiya-git** [comment]
This means that the site is not available for your region.
