### ISSUE TITLE
Example of how to use a proxy 

### ISSUE THREAD

**Issue by danielkp1234** [seiya-dev/funimation-downloader-nx#30]
** Main info: **
I'm trying to use a proxy here is the command  node funi.js --search My Hero Academia --socks 81.199.32.90:CENSORED
her is the error 
=== Funimation Downloader NX 3.2.8 ===

[ERROR] Error: 0
[ERROR] Additional info:
{
        "errno": "ECONNREFUSED",
        "code": "ECONNREFUSED",
        "syscall": "connect",
        "address": "81.199.32.90",
        "port": CENSORED
}

Script version: 3.2.8
Show ID:
Episode ID:

** Additional Info: **

**Comment by danielkp1234** [comment]
@seiya-git

**Comment by seiya-git** [comment]
Use quotes if there are spaces in the title
`funi.js --search "My Hero Academia" --socks 81.199.32.90:CENSORED`
Sorry, I use only private proxies

**Comment by seiya-git** [comment]
This means that the site is not available for your region.
