### ISSUE TITLE
Token not set!

### ISSUE THREAD

**Issue by Hunk4TH** [seiya-dev/funimation-downloader-nx#33]
Hey,

I'm new to this and finally got somewhere though when putting in my email and pass I get 

> [INFO] Token not set!
> 
> Usage: funi [options] 
> 

Maybe I'm doing something wrong? I'm using the latest beta with everything in the bin folders that needs to be there. I do have a premium funi account btw.

**Comment by deisuke1234** [comment]
you have to sign in first  in other words node funi --user "something" --pass "somethingElse"

**Comment by Hunk4TH** [comment]
Thank you that worked!
