### ISSUE TITLE
[ERROR] Failed Authentication

### ISSUE THREAD

**Issue by peppy6582** [seiya-dev/funimation-downloader-nx#35]
** Main info: **

Script version: 4.0.0 rc1
Show ID:
Episode ID:

** Additional Info: **
I am getting this error when trying to login.  I have tried both the beta, and regular.

=== Funimation Downloader NX 4.0.0-rc1 ===

[INFO] Token not set!

[ERROR] Failed Authentication.

**Comment by peppy6582** [comment]
Nevermind, it had something to do with a special character in my password

**Comment by seiya-git** [comment]
you can update to release version
