### ISSUE TITLE
Error #4: no valid Free Avails for this experience doing my hero academia episode 27 to 37

### ISSUE THREAD

**Issue by danielkp1234** [seiya-dev/funimation-downloader-nx#36]
** Main info: **
the command im using is 
node funi -s 124389 -q 9 -e 27,28,29,30,31,32,33,34,35,36,37 --simul --proxy 35.224.248.29:3128
im watching it fine in my browser 
Script version:
=== Funimation Downloader NX 4.0.0-beta1 ===
Show ID:124389
Episode ID:27 to 37

** Additional Info: **
here is the what it shows with the first episode
[INFO] My Hero Academia - S2E27 - Bizarre! Gran Torino Appears
[INFO] Available audio tracks:
[#424019] English [Simulcast] (selected)
[#699961] English [Simulcast] (selected)
[#786943] Japanese [Simulcast]
[#787926] Japanese [Simulcast]
[#559699] English [Uncut]
[#726860] English [Uncut]
[#561584] Japanese [Uncut]
[#789550] Japanese [Uncut]
[ERROR] Error #4: no valid Free Avails for this experience

and this time im watching the simulcast in english and trying to download the simulcast 
![udklip](https://user-images.githubusercontent.com/19412591/49526429-111f5a00-f8b0-11e8-8f13-743f9fa5e14a.PNG)

**Comment by seiya-git** [comment]
Thanks for report!
