### ISSUE TITLE
Can't find ffmpeg

### ISSUE THREAD

**Issue by danielkp1234** [seiya-dev/funimation-downloader-nx#37]
** Main info: **
So the script can't find ffmpeg in the modules folder I have a folder named ffmpeg that contains the ffmpeg.exe
Script version:idk the newst
Show ID:
Episode ID:

** Additional Info: **

**Comment by seiya-git** [comment]
you need change path in config:
`${__dirname}/modules/ffmpeg/ffmpeg`
