### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hits' of null

### ISSUE THREAD

**Issue by DragonVsKira** [seiya-dev/funimation-downloader-nx#38]
** Main info: **

Script version:4.0.3
Show ID:Boogiepop and Others
Episode ID:01

** Additional Info: **

A:\1.Funimation-Rip\1\funimation-downloader-nx-4.0.3>funi.bat funi --search "Boogiepop and Others"

=== Funimation Downloader NX 4.0.3 ===

[INFO] Token: ********************************

(node:14696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hits' of null
    at searchShow (A:\1.Funimation-Rip\1\funimation-downloader-nx-4.0.3\funi.js:188:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Press any key to continue . . .

**Comment by Golumpa** [comment]
This is due to Funimation's search not returning anything. If you search for the show on the Funimation site it won't find it, you need to go to the show via a direct link somewhere on the site.

As for the ID of that show, its 809999.

**Comment by storm134** [comment]
you can also view the page source and search for data-id that the show id

**Comment by seiya-git** [comment]
https://github.com/seiya-dev/funimation-downloader-nx/releases/tag/4.0.4
Fixed
