### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by OgnistyPoland** [seiya-dev/funimation-downloader-nx#39]
** Main info: **

Script version: 4.0.4 stable
Show ID: 124389
Episode ID: 0001

** Additional Info: **

`[INFO] My Hero Academia - S1E01 - Izuku Midoriya: Origin
[INFO] Available streams (Non-Encrypted):
[#787532] Japanese [Uncut] (selected)
[#293823] English [Uncut]
[#124392] Japanese [Simulcast]
[#131848] English [Simulcast]
(node:9156) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at downloadStreams (D:\funimation\funi.js:445:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Downloading shows from funimation not working when we are using "-q 0"

**Comment by seiya-git** [comment]
can you show me complete command options you input?

**Comment by OgnistyPoland** [comment]
node funi -s 124389 -e 1 --mks -a -q 0
