### ISSUE TITLE
Unable to download or pull show data.

### ISSUE THREAD

**Issue by darkhelmet2016** [seiya-dev/funimation-downloader-nx#45]
** Main info: **
When trying to do a search function or download a show will get this error, even after trying to get a fresh token to make sure login is current.

Script version:
4.3.2
Show ID:
Episode ID:

** Additional Info: **

(node:7840) UnhandledPromiseRejectionWarning: ReferenceError: URLSearchParams is
 not defined
    at getData (C:\Users\Owner\Desktop\funimation-downloader-nx-master\funi.js:6
78:33)
    at getShow (C:\Users\Owner\Desktop\funimation-downloader-nx-master\funi.js:2
56:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:7840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 3)
(node:7840) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by seiya-git** [comment]
use node v 10+

**Comment by darkhelmet2016** [comment]
Thanks, but please update the front pages then as they still say 9.4 and any other programs that need to be updates as well if it is not an issue.
