### ISSUE TITLE
how do i use this on ubuntu

### ISSUE THREAD

**Issue by AnANTKA** [seiya-dev/funimation-downloader-nx#49]
im sorry im new to these types of things on linux. how do use it? and where is the show id for funimation shows

**Comment by AnANTKA** [comment]
i figured it out but now i have this problem [WARN] MKVMerge not found, skip using this...
[WARN] FFmpeg not found, skip using this...

**Comment by seiya-git** [comment]
edit `config.main.yml` in `./modules/` directory.
