### ISSUE TITLE
Could you please update youtube-dl's Funimation script?

### ISSUE THREAD

**Issue by blackoutworm** [seiya-dev/funimation-downloader-nx#50]
Hi there.
Youtube-dl's funimation script is not working.
Since your script is, do you think you could contribute the fix to them, please?
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/funimation.py
I've looked though the script, but cannot find the problem myself. And the guys over there don't seem to care, because the script hasn't been touched in 8 months.

**Comment by seiya-git** [comment]
No, different program languages + mine based on funimation api
