### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by SciLor** [seiya-dev/funimation-downloader-nx#51]
** Main info: **

Script version: 4.4.0
Show ID: 54237
Episode ID: 1

** Additional Info: **
node funi --proxy http://35.189.90.214:3128 -s 54237 -e 1

[INFO] Selected layer: 10 (480p) @ d132fumi6di1wa.cloudfront.net
[INFO] Stream URL: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1330012/English/1330012_English_dab915ea-6872-e711-8175-020165574d09_Layer10.m3u8
[INFO] Output filename: [Funimation] Initial D - 01 [480p]
[INFO] Starting downloading ts...
[INFO] Saving stream to «[Funimation] Initial D - 01 [480p].ts»...
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Part 1 download error:
        Response code 403 (Forbidden)
[ERROR] Error: 10 parts not downloaded

**Comment by seiya-git** [comment]
Your proxy IP is banned in cloudfront, try use --ssp option

**Comment by SciLor** [comment]
--ssp wont work, there I get a 403 directly, as I am not in the USA.
The weird thing is, I can watch on the website with that proxy perfectly.

**Comment by SciLor** [comment]
Downloading via the browser over the directly link works fine, too.
https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1330012/English/1330012_English_dab915ea-6872-e711-8175-020165574d09_Layer10.m3u8

I think there must be a bug with your headers or with a leaking ip

**Comment by seiya-git** [comment]
Hm. I check it later

**Comment by seiya-git** [comment]
Can you give me your contact in Telegram or Discord?

**Comment by SciLor** [comment]
> Can you give me your contact in Telegram or Discord?
Conctact me via Telegram, please delete my message here later on
@ripitex

**Comment by Abu3safeer** [comment]
This is because the CDN for video parts is geo-locked, and ffmpeg does not use the proxy, if you use system-wide proxy it will download and work.

This is the first time I see a VOD company uses a CDN that blocks based on user location.

for now the only way is via a system wide proxy, nothing else will work.

**Comment by SciLor** [comment]
If the app downloads via ffmpeg, there is an -http_proxy option to use a proxy.

**Comment by Abu3safeer** [comment]
@SciLor -http_proxy does not work, it applier the proxy but does not use it.

**Comment by seiya-git** [comment]
@Abu3safeer I can download from France via direct link without proxy, so it's not an issue

**Comment by Abu3safeer** [comment]
I tried with ffmpeg from german and saudi ip and they never work, even with -htp_proxy.

but when I edit system settings and apply proxy there, it works.

**Comment by seiya-git** [comment]
fixed in 4.4.1

**Comment by Abu3safeer** [comment]
Great, I will try it now.
